// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/GameModeBase.h"
#include "AllAgainstTheStarsGameMde.generated.h"

/**
 * 
 */
UCLASS()
class SPAINGAMEJAM2023_API AAllAgainstTheStarsGameMde : public AGameModeBase
{
	GENERATED_BODY()
	
};
