// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "Utils/GameTypes.h"
#include "BaseManager.generated.h"

/**
 * 
 */
UCLASS()
class SPAINGAMEJAM2023_API UBaseManager : public UObject
{
	GENERATED_BODY()

public: 

	UFUNCTION(BlueprintImplementableEvent)
	void OnChangeGameStageBP(EGameModeStage newStage);

	virtual void OnChangeGameStage(EGameModeStage newStage) { OnChangeGameStageBP(newStage); }


	
};
