// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/HUD.h"
#include "AllAgainstTheStarsGameMde.h"
#include "HUDManager.generated.h"

/**
 *
 */
UCLASS()
class SPAINGAMEJAM2023_API AHUDManager : public AHUD
{
	GENERATED_BODY()

public:


	UFUNCTION(BlueprintCallable)
	void ChangeStage(EGameModeStage stage);

protected:

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<EGameModeStage, class UStageWidgets*> stageWidgets;

	UPROPERTY(VisibleAnywhere)
	class UStageWidgets* currentActiveStageWidget;
};
