// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "BaseManager.h"
#include "EnergyManager.generated.h"


DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FEnergyChangeSignature, float, currentEnergy, float, maxEnergy, float, regeneration);

/**
 *
 */
UCLASS()
class SPAINGAMEJAM2023_API UEnergyManager : public UBaseManager
{
	GENERATED_BODY()
public:

	void Restart();

	UFUNCTION(BlueprintCallable)
	void RegisterEnergyStation(class ABaseEnergyStation* station) { stationList.AddUnique(station); }

	UFUNCTION(BlueprintCallable)
	void UnregisterEnergyStation(class ABaseEnergyStation* station) { stationList.Remove(station); }

	UFUNCTION(BlueprintCallable)
	TArray<class ABaseEnergyStation*> GetStationList()const { return stationList; }

protected:

	UPROPERTY()
	TArray<class ABaseEnergyStation*> stationList;
};
