// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.


#include "Actors/BaseBeaconActor.h"
#include "Actors/GameplayManager.h"
#include "GameInstanceManagers.h"

void ABaseBeaconActor::BeginPlay()
{
	Super::BeginPlay();
	if (!GetWorld())return;

	if (auto gameInstance = Cast<UGameInstanceManagers>(GetGameInstance()))
	{
		if (auto gameplayManager = gameInstance->GetGameplaymanager())
		{
			gameplayManager->PlayerStructureCreated(this);
		}
	}

}

void ABaseBeaconActor::BeginDestroy()
{
	if (GetWorld()) {

		if (auto gameInstance = Cast<UGameInstanceManagers>(GetGameInstance()))
		{
			if (auto gameplayManager = gameInstance->GetGameplaymanager())
			{
				gameplayManager->PlayerStructureDestroyed(this);
			}
		}
	}

	Super::BeginDestroy();
}
