// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.


#include "Actors/PlaceableBaseActor.h"
#include "Components/BoxComponent.h"
#include "Actors/BuildingPawn.h"
#include "GameInstanceManagers.h"
#include "Actors/GameplayManager.h"
#include "Kismet/GameplayStatics.h"
// Sets default values
APlaceableBaseActor::APlaceableBaseActor()
{
	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	// Turret Bulding collider
	buildingCollider = CreateDefaultSubobject<UBoxComponent>("BuldingCollider");
	buildingCollider->AttachToComponent(RootComponent, FAttachmentTransformRules{ EAttachmentRule::KeepRelative, false });
	buildingCollider->SetCollisionProfileName({ "ConstructionBuilding" });
	buildingCollider->OnBeginCursorOver.AddDynamic(this, &APlaceableBaseActor::OnMouseOver);
	buildingCollider->OnEndCursorOver.AddDynamic(this, &APlaceableBaseActor::OnMouseLeaves);
	RootComponent = buildingCollider;

}

// Called when the game starts or when spawned
void APlaceableBaseActor::BeginPlay()
{
	Super::BeginPlay();

	if (!GetWorld())return;

	if (auto gameInstance = Cast<UGameInstanceManagers>(GetGameInstance()))
	{
		if (auto gameplayManager = gameInstance->GetGameplaymanager())
		{
			gameplayManager->PlayerStructureCreated(this);
		}
	}
}

void APlaceableBaseActor::Destroyed()
{

	if (GetWorld())
	{
		if (auto gameInstance = Cast<UGameInstanceManagers>(GetGameInstance()))
		{
			if (auto gameplayManager = gameInstance->GetGameplaymanager())
			{
				gameplayManager->PlayerStructureDestroyed(this);
			}
		}

	}

	Super::Destroyed();
}

void APlaceableBaseActor::OnMouseOver(UPrimitiveComponent* TouchedComponent)
{
	auto world = GetWorld();
	if (!world)return;
	if (auto pawn = Cast<ABuildingPawn>(UGameplayStatics::GetPlayerPawn(world, 0)))
	{
		pawn->SelectActor(this);
	}
}

