// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "BaseEnergyPipe.generated.h"

UCLASS()
class SPAINGAMEJAM2023_API ABaseEnergyPipe : public AActor
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	ABaseEnergyPipe();

	UFUNCTION(BlueprintCallable)
	void ConnectRoot(class UBuildingEnergyNode* new_root);

	UFUNCTION(BlueprintCallable)
	void ConnectDestiny(class UBuildingEnergyNode* new_destiny);

	UFUNCTION(BlueprintCallable)
	void ConnectRootDestiny(class UBuildingEnergyNode* new_root, class UBuildingEnergyNode* new_destiny);

	UFUNCTION(BlueprintCallable)
	class UBuildingEnergyNode* GetRoot()const;

	UFUNCTION(BlueprintCallable)
	class UBuildingEnergyNode* GetDestiny()const;

	UFUNCTION(BlueprintCallable)
	void UpdateMeshLocation();

	UFUNCTION(BlueprintCallable)
	void DisconnectRoot();

	UFUNCTION(BlueprintCallable)
	void DisconnectDestiny();

	UFUNCTION(BlueprintCallable)
	void DisconnectRootDestiny();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

	UFUNCTION(BlueprintImplementableEvent)
	void UpdateMeshToConnectBP();

	UFUNCTION(BlueprintImplementableEvent)
	void DisconnectRootBP();

	UFUNCTION(BlueprintImplementableEvent)
	void DisconnectDestinyBP();

	void UpdateMaterial();

	void UpdateDestinyEnergy();
protected:


	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	class UBuildingEnergyNode* root;

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	class UBuildingEnergyNode* destiny;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	class UStaticMeshComponent* mesh;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Visualization")
	UMaterial* material;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Visualization")
	UMaterialInstanceDynamic* materialInstance;
private:

	inline static const FName materialEnergyVariable{ "Energy" };

};
