// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "BaseEnergyStation.generated.h"

UCLASS()
class SPAINGAMEJAM2023_API ABaseEnergyStation : public AActor
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	ABaseEnergyStation();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:


	UFUNCTION(BlueprintCallable)
	void RebuildPipeGraph();

	UFUNCTION(BlueprintCallable)
	void Connect(class UBuildingEnergyNode* node);

	UFUNCTION(BlueprintCallable)
	void Disconnect(class UBuildingEnergyNode* node);

protected:

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float range = 500;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	float energy;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	class UBuildingEnergyNode* energyNode;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	class UEnergyPipeBuilder* energyBuilder;

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TArray<class UBuildingEnergyNode*> connectedComponents;



};
