// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "Actors/PlaceableBaseActor.h"
#include "BaseBeaconActor.generated.h"

/**
 *
 */
UCLASS()
class SPAINGAMEJAM2023_API ABaseBeaconActor : public APlaceableBaseActor
{
	GENERATED_BODY()
public:
	void BeginPlay()override;

	void BeginDestroy() override;
};
