// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "Actors/PlaceableBaseActor.h"
#include "Interfaces/ICombatInterface.h"
#include "BaseEnergyStation.generated.h"

UCLASS()
class SPAINGAMEJAM2023_API ABaseEnergyStation : public APlaceableBaseActor, public ICombatInterface
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	ABaseEnergyStation();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

	void Destroyed() override;

public:

	float GetRange()const;

	UFUNCTION(BlueprintCallable)
	void RebuildPipeGraph();


	UFUNCTION(BlueprintCallable)
	void Connect(class UBuildingEnergyNode* node);

	UFUNCTION(BlueprintCallable)
	void Disconnect(class UBuildingEnergyNode* node);

	// ICombatInterface 
	void DealDamage_Implementation(float ammount) const override;
	void ReceiveDamage_Implementation(float ammount) override;
	void GetCombatStats_Implementation(FCombatStats& out) const override;
	void SetCombatStats_Implementation(const FCombatStats& stats) override;
	// ~ICombatInterface
protected: 

	void RegisterToManager();
	
	void UnregisterToManager();

	void BeginDestroy()override;

protected:

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float range = 500;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	float energy;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	class UBuildingEnergyNode* energyNode;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	class UEnergyPipeBuilder* energyBuilder;

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TArray<class UBuildingEnergyNode*> connectedComponents;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FCombatStats combatStats;

	bool init = false;

};
