// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Interfaces/ICombatInterface.h"
#include "BaseEnemy.generated.h"

UCLASS()
class SPAINGAMEJAM2023_API ABaseEnemy : public AActor, public ICombatInterface
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	ABaseEnemy();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;


	UFUNCTION()
	void OnHit(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);

	virtual void OnHitCombat(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit) {}

	UFUNCTION(BlueprintImplementableEvent)
	void OnHitBP(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);

	UFUNCTION(BlueprintImplementableEvent)
	void OnHitCombatBP(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);




public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;

	UFUNCTION(BlueprintCallable)
	void Init(const FCombatStats& stats) { combatStats = stats; }

	UFUNCTION(BlueprintCallable)
	virtual void Activate();

	UFUNCTION(BlueprintImplementableEvent)
	void ActivateBP();

	// ICombatInterface 
	void DealDamage_Implementation(float ammount) const override;
	void ReceiveDamage_Implementation(float ammount) override;
	void GetCombatStats_Implementation(FCombatStats& out) const override;
	void SetCombatStats_Implementation(const FCombatStats& stats) override;
	// ~ICombatInterface

protected:

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FCombatStats combatStats;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FVector movement;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	class USphereComponent* collider;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	class UStaticMeshComponent* mesh;
};
