// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "PlaceableBaseActor.generated.h"

UCLASS()
class SPAINGAMEJAM2023_API APlaceableBaseActor : public AActor
{
	GENERATED_BODY()
	
public:	
	// Sets default values for this actor's properties
	APlaceableBaseActor();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:	
	// Called every frame
	virtual void Tick(float DeltaTime) override;
	
protected: 

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building")
	class UBoxComponent* buildingCollider;
};
