// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.


#include "Actors/Enemies/SimpleStraightEnemy.h"

void ASimpleStraightEnemy::InitMovementData(const FVector& d, float s)
{
	direction = d;
	speed = s;


}

void ASimpleStraightEnemy::Tick(float deltaTime)
{
	if (speed <= 0.01f) return;

	const FVector& currentPosition = GetActorLocation();
	const FVector nextLocation = currentPosition + direction * speed * deltaTime;
	SetActorLocation(nextLocation);
}
