// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.


#include "GameInstanceManagers.h"
#include "Energy/EnergyManager.h"
#include "HUD/HUDManager.h"
#include "Actors/GameplayManager.h"
#include "Kismet/GameplayStatics.h"

void UGameInstanceManagers::CreateEnergyManager()
{
	energyManager = NewObject<UEnergyManager>(this, { "Energy Managaer" });
	ensureMsgf(energyManager, TEXT("Error generating energy manager"));
}

void UGameInstanceManagers::Init()
{
	CreateEnergyManager();
	Super::Init();
}

void UGameInstanceManagers::ResetGameInstance()
{
	gameplayManager = nullptr;
	energyManager->Restart();
}

AHUDManager* UGameInstanceManagers::GetHudManager() const
{
	if (auto controller = UGameplayStatics::GetPlayerController(this, 0))
		return controller->GetHUD<AHUDManager>();

	return nullptr;
}

void UGameInstanceManagers::ChangeGameStage(EGameModeStage newStage)
{
	if (newStage == stage) return;

	stage = newStage;
	energyManager->OnChangeGameStage(stage);
	if (auto hudManager = GetHudManager())hudManager->ChangeStage(stage);

	if (gameplayManager) {
		gameplayManager->OnChangeGameStage(stage);
	}

	OnChangeGameStage.Broadcast(newStage);
}

void UGameInstanceManagers::Defeat()
{
	OnGameOver.Broadcast();
}

void UGameInstanceManagers::Win()
{
	OnVictory.Broadcast();
}
