// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.


#include "GameInstanceManagers.h"
#include "Energy/EnergyManager.h"
#include "HUD/HUDManager.h"
#include "TurretsManager.h"
#include "Actors/GameplayManager.h"

void UGameInstanceManagers::CreateEnergyManager()
{
	energyManager = NewObject<UEnergyManager>(this, { "Energy Managaer" });
	ensureMsgf(energyManager, TEXT("Error generating energy manager"));
}
void UGameInstanceManagers::CreateHudManager()
{
	hudManager = GetWorld()->SpawnActor<AHUDManager>(AHUDManager::StaticClass());
	ensureMsgf(hudManager, TEXT("Hud manager could not generated"));
}

void UGameInstanceManagers::CreateTurretsManager()
{
	turretsManager = NewObject<UTurretsManager>(this, { "Turrets Manager" });
	ensureMsgf(turretsManager, TEXT("Turrets manager could not be generated"));
}


void UGameInstanceManagers::Init()
{

	CreateEnergyManager();
	CreateTurretsManager();
	CreateHudManager();
	Super::Init();
}

void UGameInstanceManagers::ChangeGameStage(EGameModeStage newStage)
{
	if (newStage == stage) return; 

	stage = newStage;
	energyManager->OnChangeGameStage(stage);
	turretsManager->OnChangeGameStage(stage);
	hudManager->ChangeStage(stage);
	if (gameplayManager) {
		gameplayManager->OnChangeGameStage(stage);
	}
}

void UGameInstanceManagers::Defeat()
{
	OnGameOver.Broadcast();
	ChangeGameStage(EGameModeStage::PREPARATIONS);
}
