// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.


#include "TurretsManager.h"
#include "Actors/BaseTurret.h"
#include <algorithm>

void UTurretsManager::AddTurret(ABaseTurret* newTurret)
{
	turretsList.AddUnique(newTurret);
}

void UTurretsManager::RemoveTurret(ABaseTurret* turret)
{
	turretsList.Remove(turret);
}

void UTurretsManager::RemoveAndDestroyTurret(ABaseTurret* turret)
{
	RemoveTurret(turret);
	DestroyTurret(turret);
}

void UTurretsManager::OnChangeGameStage(EGameModeStage newStage)
{
	if(newStage != EGameModeStage::COMBAT)
		std::for_each(turretsList.begin(), turretsList.end(), [&](ABaseTurret* t) {t->SwapToMode(ETurretMode::IDLE); });
	else if (newStage == EGameModeStage::COMBAT)
	{
		std::for_each(turretsList.begin(), turretsList.end(), [&](ABaseTurret* t) {t->SwapToMode(ETurretMode::FIRING); });
	}

}

void UTurretsManager::DestroyTurret(ABaseTurret* turret)
{
	if (turret)
		turret->Destroy();
}
