// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.


#include "CodeLogic/BaseCodeNode.h"



UBaseCodeNode* UBaseCodeNode::Execute_Implementation ()
{
	return nextNode;
}


void UBaseCodeNode::SetNextNode(UBaseCodeNode* node)
{
	TFunction<void()> functor;
	nextNode = node;
}