// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.


#include "HUD/BaseUserWidget.h"

void UBaseUserWidget::OnActivate()
{
	Activate();
}

void UBaseUserWidget::OnDeactivate()
{
	Deactivate();

}
