// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.


#include "HUD/StageWidgets.h"
#include "HUD/BaseUserWidget.h"
#include "Blueprint/WidgetTree.h"
#include <algorithm>
void UStageWidgets::Activate()
{
	TArray<UWidget*> hierarchy{};
	WidgetTree->GetAllWidgets(hierarchy);

	std::for_each(hierarchy.begin(), hierarchy.end(), [](UWidget* w) {
		auto baseWidget = Cast<UBaseUserWidget>(w);
		if (baseWidget)
		{
			baseWidget->OnActivate();
		}
		});
}

void UStageWidgets::DeActivate()
{

	TArray<UWidget*> hierarchy{};
	WidgetTree->GetAllWidgets(hierarchy);

	std::for_each(hierarchy.begin(), hierarchy.end(), [](UWidget* w) {
		auto baseWidget = Cast<UBaseUserWidget>(w);
		if (baseWidget)
		{
			baseWidget->OnDeactivate();
		}
	});
}
