// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "Interfaces/ICombatInterface.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "CombatUtilsLibrary.generated.h"

/**
 *
 */
UCLASS()
class SPAINGAMEJAM2023_API UCombatUtilsLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:

	UFUNCTION(BlueprintCallable, Category = "Combat Utils")
	static void ResolveCombatStatsByActors(TScriptInterface<ICombatInterface> dealer, TScriptInterface<ICombatInterface> receiver);

	UFUNCTION(BlueprintCallable, Category = "Combat Utils")
	static void ResolveMultipleCombatStatsByActors(TScriptInterface<ICombatInterface> dealer, TArray<TScriptInterface<ICombatInterface>> receiver);

private: 

	UFUNCTION()
	static float ResolveCombatStats(const FCombatStats& dealer, const FCombatStats& receiver);

};
