// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "Interfaces/ICombatInterface.h"
#include "Actors/BaseEnemy.h"
#include "EnemyDataAsset.generated.h"


USTRUCT(BlueprintType)
struct FEnemyWave {
	GENERATED_BODY()

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TMap <TSubclassOf<ABaseEnemy>, int32> enemies;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FCombatStats combatStats;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FCombatStats scalingStats;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 numEnemies = 1;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 minLevel = 1;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 maxLevel = 4;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float spawnRate;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float waveDelay;
};

/**
 * 
 */
UCLASS()
class SPAINGAMEJAM2023_API UEnemyDataAsset : public UDataAsset
{
	GENERATED_BODY()
	
public:

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	TArray<FEnemyWave> waveData;

};
