// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "EnemyDataAsset.h"
#include "EnemySpawner.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FEnemiesSpawnSignature, class ABaseEnemy*, spawnedEnemies);
DECLARE_DYNAMIC_MULTICAST_DELEGATE(FControlSignature);

UCLASS()
class SPAINGAMEJAM2023_API AEnemySpawner : public AActor
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	AEnemySpawner();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

	UFUNCTION(BlueprintImplementableEvent)
	void OnStartSpawn();

	UFUNCTION(BlueprintImplementableEvent)
	void OnFinishSpawn();

public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;

	UFUNCTION(BlueprintCallable)
	void SpawnNewWave(UEnemyDataAsset* data);

	UFUNCTION(BlueprintCallable)
	bool IsSpawning()const;

	UFUNCTION(BlueprintCallable)
	void CancelSpawn();

private: 

	void ResetInternalData();

	void NextSubWave();

	void SpawnSubwave();

	void FinishSpawn();

	UFUNCTION()
	void OnDelayTimer();

	UFUNCTION()
	void OnSpawnTimer();

	void StopTimer(FTimerHandle& handle);
	void StartSpawnTimer(float spawnRate);

	void StartDelayTimer();

	void SpawnEnemy(TSubclassOf<ABaseEnemy> enemy);

	FCombatStats ComputeSpawnedCombatStats()const;

protected:
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	UEnemyDataAsset* currentWave;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float range = 200;

	UPROPERTY()
	FTimerHandle spawnHandle;

	UPROPERTY()
	FTimerHandle delayHandle;

	UPROPERTY(BlueprintAssignable)
	FEnemiesSpawnSignature OnEnemySpawn;

	UPROPERTY(BlueprintAssignable)
	FControlSignature OnStartWaveSpawn;

	UPROPERTY(BlueprintAssignable)
	FControlSignature OnFinishWaveSpawn;

private:
	// internals
	FEnemyWave* currentSubWave;
	int subwave_currentSubwave = 0;
	int subwave_SpawnedEnemies = 0;
	int subwave_AccumulatedProbability = 0;
};
