// All code generated by Aleix Rius for the Indie Spain Dev 2023. The code is delivered as is.

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "GameTypes.generated.h"




UENUM(BlueprintType)
enum class EGameModeStage : uint8
{
	PREPARATIONS UMETA(DisplayName = "Preparations"),
	COMBAT UMETA(DisplayName = "Combat")
};


/**
 * 
 */
UCLASS()
class SPAINGAMEJAM2023_API UGameTypes : public UObject
{
	GENERATED_BODY()
};
